# Generated by Django 5.0.7 on 2024-08-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year_of_manufacture', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('бензин', 'Gasoline'), ('дизель', 'Diesel'), ('электричество', 'Electric'), ('гибрид', 'Hybrid')], max_length=100, verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('мануальная', 'Manual'), ('автоматическая', 'Automatic'), ('вариатор', 'Variator'), ('робот', 'Robot')], max_length=100, verbose_name='Коробка передач')),
                ('mileage', models.PositiveSmallIntegerField(verbose_name='Пробег')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
